const form=document.querySelector('#clientForm'),steps=[...document.querySelectorAll('.formStep')];let current=0,signatureDrawn=false,lastPdf=null;
const pad=n=>String(n).padStart(2,'0'),today=()=>{const d=new Date();return d.getFullYear()+pad(d.getMonth()+1)+pad(d.getDate())};
function createIds(){const date=today(),key='ttrl-seq-'+date,seq=String((Number(localStorage.getItem(key))||0)+1).padStart(4,'0');localStorage.setItem(key,Number(seq));clientId.value=`CL-${date}-${seq}`;formId.value=`FRM-${date}-${seq}`;projectId.value=`PRJ-${date}-${seq}`}
function showStep(n){current=Math.max(0,Math.min(steps.length-1,n));steps.forEach((s,i)=>s.classList.toggle('active',i===current));stepLabel.textContent=`Step ${current+1} of ${steps.length}`;stepTitle.textContent=steps[current].dataset.title;progressBar.style.width=((current+1)/steps.length*100)+'%';prevStep.disabled=current===0;nextStep.disabled=current===steps.length-1;scrollTo({top:document.querySelector('.formProgress').offsetTop,behavior:'smooth'})}
function validateStep(){const invalid=[...steps[current].querySelectorAll(':invalid')][0];if(invalid){invalid.reportValidity();invalid.focus();return false}return true}
nextStep.addEventListener('click',()=>{if(validateStep())showStep(current+1)});prevStep.addEventListener('click',()=>showStep(current-1));
function addFeature(value='',priority='Need Advice',details=''){const row=document.createElement('div');row.className='featureRow';row.innerHTML=`<input name="feature_name" aria-label="Feature" placeholder="Feature or requirement" value="${value}"><select name="feature_priority" aria-label="Priority">${['Must Have','Nice to Have','Future Phase','Not Required','Need Advice'].map(x=>`<option ${x===priority?'selected':''}>${x}</option>`).join('')}</select><input name="feature_details" aria-label="Details" placeholder="Behaviour / acceptance criteria" value="${details}">`;featureTable.append(row)}
['User login & roles','Admin dashboard','Reports & analytics','Notifications'].forEach((x,i)=>addFeature(x,i<2?'Must Have':'Need Advice'));document.querySelector('#addFeature').addEventListener('click',()=>addFeature());
attachments.addEventListener('change',()=>{fileList.innerHTML=[...attachments.files].map(f=>`<li>${f.name} — ${Math.ceil(f.size/1024)} KB</li>`).join('')});
const canvas=signatureCanvas,ctx=canvas.getContext('2d');ctx.strokeStyle='#07101e';ctx.lineWidth=3;ctx.lineCap='round';let drawing=false;
function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}
function start(e){e.preventDefault();drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)}function move(e){if(!drawing)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();signatureDrawn=true}function stop(){drawing=false}
canvas.addEventListener('pointerdown',start,{passive:false});canvas.addEventListener('pointermove',move,{passive:false});['pointerup','pointerleave','pointercancel'].forEach(x=>canvas.addEventListener(x,stop));clearSignature.addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signatureDrawn=false});
signatureTime.value=new Date().toISOString();
function entries(){const data=new FormData(form),out={client_id:clientId.value,form_id:formId.value,project_id:projectId.value};for(const [k,v] of data){if(v instanceof File)continue;out[k]=out[k]?(Array.isArray(out[k])?[...out[k],v]:[out[k],v]):v}out.attachments=[...attachments.files].map(f=>f.name);out.signature_time=signatureTime.value;return out}
function save(){const out=entries();out.signature=signatureDrawn?canvas.toDataURL('image/png'):'';localStorage.setItem('ttrl-intake-draft',JSON.stringify(out));pdfStatus.textContent='Draft saved only in this browser.'}
saveDraft.addEventListener('click',save);
function restore(){const raw=localStorage.getItem('ttrl-intake-draft');if(!raw){createIds();return}try{const d=JSON.parse(raw);if(d.client_id&&d.form_id&&d.project_id){clientId.value=d.client_id;formId.value=d.form_id;projectId.value=d.project_id}else createIds();for(const [k,v] of Object.entries(d)){if(['signature','attachments','client_id','form_id','project_id'].includes(k))continue;const fields=[...form.querySelectorAll(`[name="${k}"]`)];if(!fields.length)continue;if(fields[0].type==='checkbox'){fields.forEach(f=>f.checked=(Array.isArray(v)?v:[v]).includes(f.value)||v==='on')}else fields[0].value=Array.isArray(v)?v[0]:v}if(d.signature){const im=new Image();im.onload=()=>{ctx.drawImage(im,0,0,canvas.width,canvas.height);signatureDrawn=true};im.src=d.signature}}catch{createIds()}}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function preview(){const d=entries();previewContent.innerHTML=steps.map(s=>{const names=[...s.querySelectorAll('[name]')].map(x=>x.name),items=[...new Set(names)].map(k=>{if(!d[k])return '';const field=s.querySelector(`[name="${k}"]`),q=field?.closest('label')?.querySelector('b')?.textContent||'';return `<dt>${esc(q?`${q} · ${k.replaceAll('_',' ')}`:k.replaceAll('_',' '))}</dt><dd>${esc(Array.isArray(d[k])?d[k].join(', '):d[k])}</dd>`}).join('');return items?`<section class="previewSection"><h3>${esc(s.dataset.title)}</h3><dl>${items}</dl></section>`:''}).join('');previewDialog.showModal()}
previewForm.addEventListener('click',preview);document.querySelector('.dialogClose').addEventListener('click',()=>previewDialog.close());
async function hash(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function makePdf(){const invalid=form.querySelector(':invalid');if(invalid){const step=invalid.closest('.formStep');showStep(steps.indexOf(step));setTimeout(()=>{invalid.reportValidity();invalid.focus()},350);pdfStatus.textContent='Complete all required fields before generating the PDF.';return null}if(!signatureDrawn){pdfStatus.textContent='Please draw the client signature.';showStep(12);return null}if(!window.jspdf){pdfStatus.textContent='PDF library is still loading. Please try again.';return null}const data=entries(),stamp=new Date().toISOString(),verification=await hash(JSON.stringify(data)+stamp),{jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});let y=18,page=1;const margin=16,width=178;function footer(){doc.setFontSize(8);doc.setTextColor(100);doc.text(`${formId.value} · Page ${page}`,margin,290)}function room(h=12){if(y+h>278){footer();doc.addPage();page++;y=18}}function text(t,size=10,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);doc.setTextColor(20);const lines=doc.splitTextToSize(String(t||'—'),width);room(lines.length*5+3);doc.text(lines,margin,y);y+=lines.length*5+3}doc.setTextColor(0,130,170);text('TTRL CLIENT REQUIREMENT & ACKNOWLEDGEMENT',15,true);text(`Client ID: ${clientId.value}   Form ID: ${formId.value}`,9);text(`Project ID: ${projectId.value}   Generated: ${stamp}`,9);y+=3;for(const s of steps){room(18);doc.setDrawColor(60,190,220);doc.line(margin,y,width+margin,y);y+=7;text(s.dataset.title.toUpperCase(),12,true);const names=[...new Set([...s.querySelectorAll('[name]')].map(x=>x.name))];for(const k of names){if(k==='signature_confirm')continue;const v=data[k];if(!v)continue;const field=s.querySelector(`[name="${k}"]`),q=field?.closest('label')?.querySelector('b')?.textContent||'';text((q?`${q} · `:'')+k.replaceAll('_',' ').toUpperCase(),8,true);text(Array.isArray(v)?v.join(', '):v,10)}}room(55);text('CLIENT SIGNATURE',10,true);doc.addImage(canvas.toDataURL('image/png'),'PNG',margin,y,80,28);y+=34;text(`Signed by: ${data.signatory_name||data.full_name||'—'} · ${data.signature_time}`,9);room(25);text('VERIFICATION HASH',8,true);text(verification,8);text('This client-generated PDF records submitted requirements and acknowledgement. It is not a final quotation or contract.',8);footer();const blob=doc.output('blob'),filename=`REQ-${today()}-${formId.value.split('-').pop()}-${(data.full_name||'CLIENT').replace(/[^a-z0-9]+/gi,'-')}.pdf`;lastPdf={blob,filename};pdfStatus.textContent=`PDF ready: ${filename}`;return lastPdf}
downloadPdf.addEventListener('click',async()=>{const p=await makePdf();if(!p)return;const a=document.createElement('a');a.href=URL.createObjectURL(p.blob);a.download=p.filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)});
sharePdf.addEventListener('click',async()=>{const p=await makePdf();if(!p)return;const file=new File([p.blob],p.filename,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){await navigator.share({title:'TTRL Project Requirement',text:`Client requirement ${formId.value}`,files:[file]})}else{pdfStatus.textContent='Direct file sharing is not supported here. Download the PDF, then attach it to WhatsApp or email.'}});
restore();showStep(0);
