const toggle=document.querySelector('.menuToggle');
const nav=document.querySelector('.navlinks');
if(toggle&&nav){const close=()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰'};toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',close));addEventListener('keydown',event=>{if(event.key==='Escape')close()})}

const WORK_CONTEXT=`Mosin Liyakat Shaikh, professionally known as Mosin Shaikh, is an Architect and Founder of T Technology Research Lab (TTRL).
TTRL works on AI agents, chatbots, automation, machine learning, AI analytics, websites, web applications, mobile apps, desktop software, enterprise software, SaaS, FinTech, payments, lending, risk engines, cybersecurity, cloud, DevOps, data engineering, Excel automation, VBA, Power BI and consulting.
Excel services include advanced workbooks, MIS reports, financial models, budget sheets, KPI dashboards, sales and expense tracking, VBA macros, one-click processing, validation, invoices, salary and GST calculators.
Integration services include Excel with SQL, CRM, ERP and APIs; inventory, stock, accounting, attendance, payroll, purchasing, vendor and asset management systems.
Selected work: T Financial Intelligence OS is an open-source research OS for market intelligence, paper trading, backtesting and risk analysis. VortX Agentic OS is an agentic AI command architecture for evidence-led orchestration and enterprise automation. T Technology Research Lab is the ongoing research and product-building initiative.
Public project status: T Financial Intelligence OS is under active research/development; VortX Agentic OS is a research-stage architecture; TTRL is an ongoing initiative. Exact private start dates, delivery dates or client information are not published and must never be invented.
Process: discovery and requirements, architecture/design, development, validation/testing, deployment, monitoring and improvement. A delivery estimate requires project scope.
Contact: WhatsApp +91 89760 99500. Email mohsin.say80@proton.me. LinkedIn: Mosin Shaikh. GitHub: github.com/mosinlshaikh.
The assistant must answer only questions related to Mosin, TTRL, projects, professional services, software, AI, data, business automation and technology. It must politely refuse unrelated personal, entertainment, political, medical, legal or general lifestyle requests.`;

const FAQ=[
{keys:['service','services','what do you do','work','portfolio'],answer:'TTRL provides end-to-end technology services: websites and web apps, AI agents and automation, Excel/VBA and Power BI, enterprise integrations, data engineering, FinTech systems, cloud/DevOps, cybersecurity and architecture consulting.'},
{keys:['website','web site','web development','ecommerce','e-commerce'],answer:'Yes. TTRL builds luxury business and portfolio websites, responsive web applications, e-commerce and corporate websites, custom frontend/backend systems, SEO, performance optimization and deployment.'},
{keys:['timeline','project status','roadmap','when complete','stage'],answer:'Public project timeline/status:\n• T Financial Intelligence OS — active research and development.\n• VortX Agentic OS — research-stage architecture.\n• T Technology Research Lab — ongoing research and product initiative.\nExact private start or delivery dates are not published. A client delivery timeline is estimated after discovery and scope definition.'},
{keys:['process','how do you build','development process'],answer:'The delivery process is: 1) discovery and requirements, 2) architecture and experience design, 3) development, 4) validation and testing, 5) deployment, and 6) monitoring and continuous improvement.'},
{keys:['excel','vba','macro','power bi','dashboard','mis'],answer:'Excel and business automation includes advanced workbooks, MIS and KPI dashboards, financial models, budget planning, sales/expense tracking, VBA macros, automated invoices, salary/GST calculators, Power BI reports and one-click data processing.'},
{keys:['ai','agent','chatbot','machine learning'],answer:'TTRL works on AI agents, chatbots, intelligent automation, machine learning, AI analytics and evidence-led agentic system architecture. Solutions are designed around measurable business requirements.'},
{keys:['fintech','payment','lending','risk'],answer:'FinTech capabilities include payment systems, lending platforms, financial intelligence, backtesting, paper trading and risk-engine architecture.'},
{keys:['integration','sql','crm','erp','api','database'],answer:'TTRL can integrate Excel and applications with SQL databases, CRM, ERP and APIs, including synchronization, validation and management-system workflows.'},
{keys:['price','cost','budget','quote','charges'],answer:'Pricing depends on scope, integrations, complexity and timeline. Share your requirements on WhatsApp at +91 89760 99500 or email mohsin.say80@proton.me for a project estimate.'},
{keys:['contact','whatsapp','email','linkedin','github'],answer:'Contact Mosin directly:\n• WhatsApp: +91 89760 99500\n• Email: mohsin.say80@proton.me\n• LinkedIn: Mosin Shaikh\n• GitHub: github.com/mosinlshaikh'},
{keys:['mosin','founder','architect','ttrl'],answer:'Mosin Liyakat Shaikh, professionally known as Mosin Shaikh, is the Architect and Founder of T Technology Research Lab (TTRL), focused on AI systems, software architecture, automation, data and digital products.'}
];

const allowed=/\b(mosin|shaikh|ttrl|technology|tech|software|website|web|app|mobile|desktop|saas|ai|agent|chatbot|automation|machine learning|excel|vba|macro|power bi|dashboard|data|database|sql|crm|erp|api|cloud|devops|security|cyber|fintech|payment|lending|risk|project|timeline|roadmap|service|work|portfolio|architect|development|code|programming|python|javascript|java|go|rust|analytics|business|inventory|payroll|accounting|contact|whatsapp|email|linkedin|github|price|cost|budget|quote|process)\b/i;
function localAnswer(q){if(!allowed.test(q))return 'I can only answer questions related to Mosin Shaikh, TTRL work, projects, services and technology.';const s=q.toLowerCase();let best=null,score=0;for(const item of FAQ){const n=item.keys.reduce((a,k)=>a+(s.includes(k)?1:0),0);if(n>score){score=n;best=item}}return best?best.answer:'This is a technology-related question. For a broader generated answer, enable On‑Device AI on a compatible WebGPU device. You can also ask about TTRL services, projects, timeline, architecture or contact details.'}

const fab=document.querySelector('.aiFab'),panel=document.querySelector('.aiPanel'),closeAI=document.querySelector('.aiClose'),form=document.querySelector('.aiForm'),input=document.querySelector('#aiInput'),messages=document.querySelector('.aiMessages'),suggestions=document.querySelector('.aiSuggestions'),enable=document.querySelector('.enableAI'),status=document.querySelector('.aiStatus'),progress=document.querySelector('.aiProgress');
let engine=null,aiReady=false,loading=false;
function openPanel(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),100)}
function closePanel(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function addMessage(text,who='bot',extra=''){const d=document.createElement('div');d.className='aiMsg '+who+(extra?' '+extra:'');d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
async function ask(q){addMessage(q,'user');input.value='';if(!allowed.test(q)){addMessage('I can only answer questions related to Mosin Shaikh, TTRL work, projects, professional services and technology.');return}if(!aiReady){addMessage(localAnswer(q));return}const wait=addMessage('Thinking locally on your device…','bot','thinking');try{const reply=await engine.chat.completions.create({messages:[{role:'system',content:WORK_CONTEXT},{role:'user',content:q}],temperature:.25,max_tokens:420});wait.remove();addMessage(reply.choices[0].message.content.trim())}catch(e){wait.remove();addMessage('The local AI could not complete that response. Knowledge mode is still available. '+localAnswer(q))}}
fab?.addEventListener('click',openPanel);closeAI?.addEventListener('click',closePanel);addEventListener('keydown',e=>{if(e.key==='Escape'&&panel?.classList.contains('open'))closePanel()});form?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(q)ask(q)});suggestions?.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')ask(e.target.textContent)});
enable?.addEventListener('click',async()=>{if(aiReady||loading)return;if(!('gpu'in navigator)){addMessage('On-device AI needs a WebGPU-compatible browser/device. Knowledge mode will continue to work without any download.');return}loading=true;enable.disabled=true;progress.hidden=false;addMessage('On-device AI setup started. This downloads a large model once and may use about 1 GB of device memory.');try{const webllm=await import('https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm@0.2.84/+esm');engine=await webllm.CreateMLCEngine('Qwen2.5-0.5B-Instruct-q4f16_1-MLC',{initProgressCallback:p=>{const n=Math.max(0,Math.min(100,Math.round((p.progress||0)*100)));progress.querySelector('span').style.width=n+'%';progress.querySelector('small').textContent=p.text||('Preparing local AI… '+n+'%')}});aiReady=true;status.innerHTML='<i></i>On-device AI ready';enable.textContent='AI enabled';progress.hidden=true;addMessage('On-device AI is ready. It runs in this browser without an API. Ask any work or technology question.')}catch(e){progress.hidden=true;enable.disabled=false;addMessage('This device could not start the local model. Knowledge mode remains fully available.');console.error(e)}finally{loading=false}});
