const toggle=document.querySelector('.menuToggle');
const nav=document.querySelector('.navlinks');
if(toggle&&nav){const close=()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='☰'};toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',close));addEventListener('keydown',event=>{if(event.key==='Escape')close()})}

const WORK_CONTEXT=`Mosin Liyakat Shaikh, professionally known as Mosin Shaikh, is an Architect and Founder of T Technology Research Lab (TTRL).
BRAND IDENTITY:
Official name: T Technology Research Lab. Short name: TTRL. Founder and Architect: Mosin Liyakat Shaikh, professionally known as Mosin Shaikh.
Positioning: a research-led technology architecture, development and business automation practice. Brand promise: research deeply, architect responsibly and build practical technology that creates measurable business value.
Tagline used in branded material: INNOVATE • RESEARCH • DEVELOP.
Do not describe TTRL as a large corporation, claim unverified awards, invent employees, offices, clients, certifications or completed products.
MISSION: research deeply, architect responsibly and build practical technology that creates measurable business value.
CAPABILITIES:
1. Websites and web applications: luxury portfolios, corporate sites, responsive business websites, e-commerce, custom frontend/backend systems, SEO, performance and deployment.
2. Applications and products: mobile apps, desktop software, enterprise software, SaaS platforms and product development.
3. AI: AI agents, chatbots, intelligent workflow automation, machine learning, AI analytics and agentic system architecture.
4. Excel and Office automation: advanced Excel, MIS, financial models, budgets, KPI/sales/expense/project/performance dashboards, VBA macros, validation, invoices, salary/GST calculators and automated reporting.
5. Data and BI: Power BI, interactive dashboards, executive reports, real-time analytics, visualization, cleaning, migration, consolidation, analysis, transformation and data engineering.
6. Integrations: Excel or applications with SQL, CRM, ERP, databases and APIs; synchronization and automated workflows.
7. Management systems: inventory, stock, accounting, attendance, payroll, purchase, vendor and asset management.
8. FinTech: payment systems, lending platforms, financial intelligence and risk engines.
9. Other technical areas: blockchain solutions, cybersecurity platforms, audits, monitoring, cloud, DevOps, deployment and infrastructure.
10. Consulting: discovery, architecture design, CTO as a Service and technical consulting.\nCLIENT INTAKE FORM: TTRL provides a separate 13-step Client Requirement & Acknowledgement Form at intake.html. It records client identity, project goals, selected services, feature priorities, exclusions, hosting/domain, branding/logo, data/integrations, deliverables, timeline/budget, responsibilities, attachments list, acknowledgements and a touch/mouse digital signature. It generates IDs in TYPE-YYYYMMDD-NNNN format, saves a local browser draft, creates a signed PDF with timestamp and SHA-256 verification hash, and supports Web Share where available. It is an initial requirement record, not a quotation or final contract.
SELECTED WORK:
T Financial Intelligence OS: open-source research OS for market intelligence, paper trading, backtesting and risk analysis. Public status: active research/development.
VortX Agentic OS: agentic AI command architecture for evidence-led orchestration, automation and enterprise systems. Public status: research-stage architecture.
T Technology Research Lab: ongoing research and product-building initiative.
DELIVERY PROCESS:
1. Discovery: understand the business, users, problem, current workflow, desired outcome, constraints and priorities.
2. Requirement acknowledgement: client records needs, exclusions, hosting/domain, branding/logo, integrations, deliverables, budget, responsibilities, notes and approval details in the 13-step intake form.
3. Analysis and clarification: TTRL reviews the submission, identifies missing information, risks, dependencies and assumptions, then sends focused questions.
4. Scope and architecture: define modules, data flows, technology stack, security, milestones, acceptance criteria, exclusions and third-party requirements.
5. Proposal and quotation: issue a separate written scope, phased timeline, commercial terms and quotation. The intake form itself is not a quotation or contract.
6. UX and design: wireframes, visual direction, content structure and approval where relevant.
7. Development: milestone-based implementation with appropriate version control and internal validation.
8. Quality validation: functional, responsive, performance, security and acceptance checks appropriate to the agreed scope.
9. Deployment and handover: release, configuration, documentation, training or source handover according to the agreement.
10. Support and improvement: maintenance, monitoring, fixes and future phases only under agreed support terms.
CLIENT COMMUNICATION: remain professional, transparent and concise. Ask one focused clarification at a time when essential information is missing. Never pressure a client. Clearly separate confirmed facts, assumptions, recommendations, exclusions and third-party costs.
DELIVERABLES: may include source code, deployment, admin panel, database, documentation, user manual, training, design files, testing report, backup, store publishing and maintenance when explicitly included in scope.
COMMERCIAL POLICY: pricing and timeline depend on verified scope. Do not invent a rate, discount, guarantee, deadline, payment term or legal commitment. Domain, hosting, payment gateway, API, licence, messaging, cloud, app-store and other third-party charges may be separate.
QUALITY POLICY: prefer secure, maintainable and measurable solutions; never claim zero risk, perfect security, guaranteed rankings, guaranteed business results or regulatory approval.
TIMELINES AND PRICING: depend on scope, integrations, complexity and validation requirements. Never invent fixed prices, private dates, client names or guaranteed schedules.
CONTACT: WhatsApp +91 89760 99500; email mohsin.say80@proton.me; LinkedIn Mosin Shaikh; GitHub github.com/mosinlshaikh.
LANGUAGE POLICY:
Detect the language and script of the user's latest message and answer in the same language by default. Support English, Hinglish, Hindi, Marathi and other Indian languages including Urdu, Gujarati, Bengali, Punjabi, Tamil, Telugu, Kannada and Malayalam. Also support major foreign languages such as Arabic, French, Spanish, German, Portuguese, Russian, Chinese, Japanese and Korean when the on-device model can produce them reliably. Preserve product names, URLs, email addresses and technical terms accurately. If a translation may change a legal, commercial or technical meaning, retain the original term in parentheses. If language is unclear, use simple English. Never claim human fluency; focus on clear client communication.
ANSWER METHOD:
First identify the client's intent. Give the direct answer, then relevant options or process, then the next action. For project enquiries, collect only missing essentials: business goal, users, must-have features, exclusions, existing systems/data, integrations, deadline, budget range and desired deliverables. Recommend the Client Requirement Form for detailed discovery. Do not repeatedly give the same generic service answer when the question asks about cost, timeline, process, feasibility, comparison, security, hosting, branding or a specific technology.
RULES: Answer only about Mosin, TTRL, public projects, professional services, project discovery, software, AI, data, automation and technology. Be concise, factual and helpful. If information is unpublished or unknown, say so and ask a focused clarification. Never invent private client information, credentials, project status, quotations, dates, capabilities or guarantees. Do not accept payments, sign contracts, confirm bookings or promise work on Mosin's behalf. Refuse unrelated personal, entertainment, political, medical, legal and lifestyle requests.`;

const FAQ=[
{keys:['branding','brand identity','logo design','ब्रांडिंग','लोगो','ब्रँडिंग','ब्रँड','ब्रांड','brand'],answer:'TTRL can help with brand discovery, logo direction, colour and typography systems, visual identity, website application and practical brand guidelines. Exact deliverables are confirmed in the project scope.'},
{keys:['quotation number','quotation process','quotation','proposal','कोटेशन','अंदाजपत्रक','प्रस्ताव'],answer:'The client first submits requirements. TTRL reviews scope, dependencies, exclusions and questions, then issues a separate written proposal and quotation. The intake acknowledgement is not itself a quotation or contract.'},
{keys:['client process','work process','काम कैसे शुरू','कामाची प्रक्रिया','project kaise start','project shuru'],answer:'Start with discovery and the 13-step Client Requirement Form. TTRL then analyses the submission, asks focused clarifications, defines scope and architecture, prepares a proposal and quotation, and proceeds through design, development, testing, deployment and agreed support.'},
{keys:['what languages','language support','hindi','hinglish','marathi','हिंदी','मराठी','भाषा','اردو','ગુજરાતી','বাংলা','தமிழ்','తెలుగు','ಕನ್ನಡ','മലയാളം'],answer:'TTRL Work AI can understand and respond in English, Hinglish, Hindi, Marathi and multiple Indian or international languages. It normally replies in the same language and script as the latest question; technical names and contact details remain unchanged.'},

{keys:['client form','requirement form','project form','intake form','start requirement'],answer:'Use the TTRL Client Requirement & Acknowledgement Form at intake.html. It guides the client through 13 steps covering identity, scope, services, product priorities, hosting, branding, data, deliverables, budget, responsibilities, notes, acknowledgement and signature.'},
{keys:['form id','client id','project id','reference number'],answer:'The intake page generates separate Client, Form and Project references using TYPE-YYYYMMDD-NNNN, for example CL-20260718-0001, FRM-20260718-0001 and PRJ-20260718-0001.'},
{keys:['form pdf','requirement pdf','signed pdf','share pdf'],answer:'After completing required fields and drawing a signature, the client can generate a requirement PDF containing answers, question references, timestamp, signature and SHA-256 verification hash. Supported mobile devices can share the PDF through the system share sheet.'},
{keys:['digital signature','sign form','finger signature','mouse signature'],answer:'The intake form includes a signature canvas that works with finger, touch screen or mouse. The signature is embedded in the generated requirement PDF. This client-side record is not a substitute for a secure server-audited e-signature platform or final contract.'},

{keys:['who is mosin','about mosin','mosin shaikh','mosin liyakat','founder','architect'],answer:'Mosin Liyakat Shaikh, professionally known as Mosin Shaikh, is the Architect and Founder of T Technology Research Lab (TTRL). His work focuses on AI systems, software architecture, automation, data, FinTech and digital products.'},
{keys:['what is ttrl','about ttrl','technology research lab','research lab'],answer:'T Technology Research Lab (TTRL) is an ongoing technology research and product-building initiative founded by Mosin Shaikh. Its approach is to research deeply, architect responsibly and build practical systems that create measurable value.'},
{keys:['all services','services do you provide','service portfolio','what do you do','your work','capabilities'],answer:'TTRL provides websites and applications, AI agents and automation, Excel/VBA and Power BI, data engineering and integrations, enterprise management systems, FinTech, cybersecurity, cloud/DevOps, SaaS/product development and architecture consulting.'},
{keys:['build website','build my website','can you build my website','website development','business website','portfolio website','corporate website','ecommerce','e commerce'],answer:'Yes. TTRL builds luxury portfolio and business websites, corporate and e-commerce sites, responsive web applications, custom frontend/backend systems, SEO, performance optimization and deployment.'},
{keys:['website process','how website','steps for website','website timeline'],answer:'A website project normally moves through discovery, content/requirements, information architecture, visual design, responsive development, testing, SEO/performance checks and deployment. Exact timing depends on page count, content, integrations and revision scope.'},
{keys:['domain','hosting','deploy website','website deployment','github pages'],answer:'TTRL can guide domain setup, hosting selection, deployment, HTTPS and monitoring. The appropriate hosting platform depends on whether the website is static, dynamic, database-driven or e-commerce.'},
{keys:['seo','google ranking','search engine','google search'],answer:'Website SEO work can include semantic structure, titles and descriptions, structured data, sitemap, robots rules, performance, mobile usability and Search Console setup. No ethical provider can guarantee a permanent first position on Google.'},
{keys:['mobile app','android app','ios app','application development'],answer:'TTRL can architect and develop mobile applications according to business requirements. Platform, offline capability, backend, notifications, payments and integrations are selected during discovery.'},
{keys:['desktop software','desktop app','windows software'],answer:'Desktop software can be designed for operational workflows, data processing, internal management and automation. Technology and packaging depend on the target operating systems and integration requirements.'},
{keys:['saas','software as a service','subscription platform'],answer:'TTRL can design SaaS platforms including product discovery, multi-user architecture, roles, billing-ready workflows, dashboards, data models, deployment and monitoring. Exact scope requires discovery.'},
{keys:['ai services','ai agent','agents','chatbot','machine learning','agentic ai'],answer:'TTRL works on AI agents, chatbots, intelligent workflow automation, machine learning, AI analytics and evidence-led agentic architecture. The AI approach is selected around the business problem, data, privacy and measurable outcome.'},
{keys:['automation','business automation','workflow automation','automate business'],answer:'Business automation can connect forms, Excel, databases, APIs, reports and approval workflows to reduce repetitive work and errors. The first step is mapping the current process and identifying high-value automation points.'},
{keys:['excel services','excel automation','advanced excel','spreadsheet'],answer:'Excel services include advanced workbooks, MIS reports, financial models, budgets, KPI dashboards, sales/expense/project tracking, validation, automated reporting and management sheets.'},
{keys:['vba','macro','one click','excel macro'],answer:'VBA solutions can automate repetitive Excel work, one-click data processing, validation, report generation, invoices, salary calculations, GST calculations and custom workflow controls.'},
{keys:['power bi','bi dashboard','interactive dashboard','executive report'],answer:'Power BI services include interactive dashboards, executive reporting, data visualization, KPI monitoring and business intelligence. Data sources and refresh requirements are defined during discovery.'},
{keys:['data cleaning','data migration','data consolidation','data transformation','data engineering'],answer:'Data services cover cleaning, migration, entry automation, consolidation, analysis, transformation, reporting automation and data engineering. Validation rules are used to protect accuracy.'},
{keys:['sql','database','api integration','crm','erp','data sync','integration'],answer:'TTRL can integrate Excel or applications with SQL databases, CRM, ERP and APIs, including synchronization, validation, automated processing and reporting workflows.'},
{keys:['inventory','stock management'],answer:'Inventory and stock systems can cover products, inward/outward movement, stock levels, reorder alerts, vendors, purchases, audit history and management reporting. Final modules depend on operations.'},
{keys:['attendance','payroll','salary system','employee management'],answer:'Employee systems can include attendance, payroll workflows, salary calculations, employee records, controls and reports. Compliance-specific rules must be provided and validated by the client.'},
{keys:['accounting','purchase management','vendor management','asset management'],answer:'TTRL can build operational management systems for accounting workflows, purchasing, vendors and assets, with role-based controls, validations and reporting based on business requirements.'},
{keys:['fintech','financial technology','payment system','lending platform','risk engine'],answer:'FinTech capabilities include payment-system architecture, lending platforms, financial intelligence and risk engines. Production financial systems require strong security, compliance review and rigorous validation.'},
{keys:['financial intelligence os','t financial','paper trading','backtesting','market intelligence'],answer:'T Financial Intelligence OS is an open-source research operating system for market intelligence, paper trading, backtesting and risk analysis. Its public status is active research and development.'},
{keys:['vortx','agentic os','vortx agentic'],answer:'VortX Agentic OS is a research-stage agentic AI command architecture for evidence-led orchestration, automation and enterprise systems. It is presented as research architecture, not a claimed finished commercial product.'},
{keys:['my project take','client project','delivery estimate','how long will','project duration'],answer:'A client project duration can be estimated only after requirements and scope are defined. Features, integrations, content readiness, testing, feedback and approvals all affect the schedule. Share a brief for a realistic phased timeline.'},
{keys:['project timeline','project status','roadmap','when complete','delivery time','how long'],answer:'Public status:\n• T Financial Intelligence OS — active research/development.\n• VortX Agentic OS — research-stage architecture.\n• TTRL — ongoing research and product initiative.\nClient delivery timelines depend on scope, integrations, testing and approvals; unpublished dates are not invented.'},
{keys:['development process','project process','how do you build','start project','working process'],answer:'The delivery process is: 1) discovery and requirements, 2) scope and architecture, 3) UX/design where needed, 4) development, 5) validation/testing, 6) deployment, and 7) monitoring and improvement.'},
{keys:['requirements','what do you need','project details','brief'],answer:'To assess a project, share the business goal, target users, required features, current workflow, data sources, integrations, preferred deadline and budget range. TTRL can then define scope and architecture.'},
{keys:['price','pricing','cost','budget','quote','charges','how much'],answer:'Pricing depends on scope, features, integrations, complexity, testing and delivery requirements. Share a project brief on WhatsApp +91 89760 99500 or email mohsin.say80@proton.me for an estimate.'},
{keys:['support','maintenance','after delivery','monitoring'],answer:'Post-delivery support can include issue resolution, monitoring, updates, performance checks and planned improvements. Support terms should be defined in the project scope.'},
{keys:['security','cybersecurity','audit','secure system'],answer:'Security work can include secure architecture, access controls, validation, monitoring and audit-oriented review. The exact approach depends on data sensitivity, threat model and regulatory requirements.'},
{keys:['cloud','devops','infrastructure','deployment','monitoring system'],answer:'Cloud and DevOps capabilities include deployment architecture, infrastructure setup, release workflows, monitoring and operational improvements. Platform choice depends on workload and budget.'},
{keys:['blockchain'],answer:'TTRL includes blockchain solutions within its broader technology portfolio. A suitable design depends on whether the problem genuinely requires distributed trust, auditability or tokenized workflows.'},
{keys:['consulting','technical consulting','cto as a service','architecture design','product discovery'],answer:'Consulting services include product discovery, architecture design, technical strategy, CTO as a Service and implementation guidance. The engagement begins by clarifying business goals and constraints.'},
{keys:['source code','ownership','code handover'],answer:'Source-code ownership and handover should be defined clearly in the project agreement. Requirements may differ for custom development, licensed components and open-source dependencies.'},
{keys:['nda','confidential','privacy'],answer:'Confidential project information should be handled under agreed privacy and NDA terms where required. Sensitive credentials must never be submitted through the public website assistant.'},
{keys:['contact','whatsapp','email','linkedin','github','talk to mosin'],answer:'Contact Mosin directly:\n• WhatsApp: +91 89760 99500\n• Email: mohsin.say80@proton.me\n• LinkedIn: Mosin Shaikh\n• GitHub: github.com/mosinlshaikh'},
{keys:['available','availability','hire','collaboration'],answer:'Mosin is available for select technology collaborations. Share the project goal and requirements through WhatsApp or email to discuss fit and next steps.'},
{keys:['python'],answer:'Python is widely used for automation, data processing, AI/ML, APIs and backend services. For a TTRL project, the technology stack is chosen only after requirements and deployment constraints are clear.'},
{keys:['javascript','typescript','frontend'],answer:'JavaScript and TypeScript are commonly used for interactive web interfaces and server applications. TTRL selects frontend and backend technologies according to the project rather than forcing one stack.'},
{keys:['programming language','tech stack','which technology','framework'],answer:'The correct technology stack depends on product type, integrations, expected users, performance, security, maintainability and budget. TTRL defines the stack during architecture and does not claim one tool fits every project.'}
];

function normalize(q){return q.toLowerCase().replace(/[^a-z0-9+#.]+/g,' ').replace(/\\s+/g,' ').trim()}
function faqMatch(q){const s=normalize(q);let best=null,score=0;for(const item of FAQ){let n=0;for(const key of item.keys){const k=normalize(key);if(s.includes(k))n+=k.includes(' ')?3:2}if(n>score){score=n;best=item}}return score>0?best:null}
const SCOPE_ROOTS=['mosin','shaikh','ttrl','technolog','software','website','web app','mobile app','desktop app','saas','artificial intelligence',' ai ','agent','chatbot','automat','machine learning','excel','vba','macro','power bi','dashboard','data','database','sql','crm','erp','api','cloud','devops','security','cyber','fintech','payment','lending','risk','project','timeline','roadmap','service','work','portfolio','architect','develop','coding','programming','python','javascript','java','golang','rust','analytic','business','inventory','payroll','accounting','contact','whatsapp','email','linkedin','github','price','pricing','cost','budget','quote','process','system','integration','product','backend','frontend','ecommerce','hosting','seo','support','maintenance','kya banate','kaam','seva','jankari','jaankari','batao','banao'];
const MULTILINGUAL_SCOPE=['नमस्ते','नमस्कार','सलाम','सेवा','काम','वेबसाइट','सॉफ्टवेयर','किंमत','खर्च','वेळ','प्रक्रिया','संपर्क','माहिती','तंत्रज्ञान','प्रकल्प','स्वयंचलन','काय बनवता','किती पैसे','कितना समय','संपर्क','ગુજરાતી','વેબસાઇટ','સેવા','કિંમત','যোগাযোগ','ওয়েবসাইট','পরিষেবা','தொழில்நுட்பம்','இணையதளம்','சேவை','ధర','వెబ్‌సైట్','సేవ','ತಂತ್ರಜ್ಞಾನ','ವೆಬ್‌ಸೈಟ್','ಸೇವೆ','സാങ്കേതികവിദ്യ','വെബ്സൈറ്റ്','സേവനം','خدمات','ویب سائٹ','رابطہ','السعر','الموقع','الخدمات','servicio','precio','sitio web','service','prix','site web','dienstleistung','preis','website','serviço','preço','сайт','услуги','цена','网站','服务','价格','ウェブサイト','サービス','価格','웹사이트','서비스','가격'];
const GREETINGS=['hi','hello','hey','salam','salaam','namaste','namaskar','good morning','good evening','नमस्ते','नमस्कार','सलाम','السلام عليكم','مرحبا','hola','bonjour','hallo','olá','привет','你好','こんにちは','안녕하세요'];
function isGreeting(q){const s=normalize(q);return GREETINGS.some(g=>s===g||s.startsWith(g+' '))}
function priorityAnswer(q,previous=''){const s=normalize(q),context=normalize(previous+' '+q);
const wantsPrice=/(how much|price|pricing|cost|budget|quote|charges|estimate)/.test(s);
const wantsDuration=/(how long|duration|delivery time|timeline|when.*ready|when.*complete)/.test(s);
const wantsContact=/(contact|whatsapp|email|linkedin|github|talk to mosin|reach)/.test(s);
const wantsRequirements=/(what do you need|requirements|project brief|details needed|how to start)/.test(s);
if(wantsPrice){if(/e commerce|ecommerce/.test(context))return 'E-commerce website pricing depends on product count, payment gateway, customer accounts, inventory, shipping rules, admin dashboard, integrations, design and testing. Share these requirements for an exact quotation on WhatsApp +91 89760 99500 or email mohsin.say80@proton.me.';if(/website|web app|web application/.test(context))return 'Website pricing depends on page count, content, custom design, backend, forms, integrations, SEO and deployment. Share a project brief for an exact quotation on WhatsApp +91 89760 99500 or email mohsin.say80@proton.me.';return 'Pricing depends on scope, features, integrations, complexity, testing and delivery requirements. Share a project brief on WhatsApp +91 89760 99500 or email mohsin.say80@proton.me for an estimate.'}
if(wantsDuration){if(/my project|client|website|app|system|software/.test(context))return 'A realistic delivery timeline requires confirmed scope. Features, integrations, content readiness, design revisions, testing and approvals affect duration. Share the project brief and TTRL can propose a phased schedule.';return null}
if(wantsContact)return 'Contact Mosin directly:\n• WhatsApp: +91 89760 99500\n• Email: mohsin.say80@proton.me\n• LinkedIn: Mosin Shaikh\n• GitHub: github.com/mosinlshaikh';
if(wantsRequirements)return 'To assess your project, share the business goal, target users, required features, current workflow, content/data sources, integrations, preferred deadline and budget range. TTRL can then define scope, architecture and phases.';
return null}
function inScope(q,previous=''){if(priorityAnswer(q,previous)||faqMatch(q)||isGreeting(q))return true;const raw=(q+' '+previous).toLowerCase(),s=' '+normalize(q)+' ';return SCOPE_ROOTS.some(root=>s.includes(root))||MULTILINGUAL_SCOPE.some(root=>raw.includes(root))}
function localAnswer(q,previous=''){if(isGreeting(q))return 'Hello! I am TTRL Work AI. Ask me about Mosin Shaikh, websites, software, AI, automation, Excel, Power BI, projects, process, pricing or contact details.';const priority=priorityAnswer(q,previous);if(priority)return priority;const match=faqMatch(q);if(match)return match.answer;if(!inScope(q,previous))return 'I can only answer questions related to Mosin Shaikh, TTRL work, projects, professional services and technology.';return 'Your question is within technology, but this device is currently using the lightweight knowledge mode. Ask a more specific question about websites, AI, automation, Excel, Power BI, software architecture, projects, process, pricing or contact—or enable On‑Device AI on a compatible WebGPU device.'}

const fab=document.querySelector('.aiFab'),panel=document.querySelector('.aiPanel'),closeAI=document.querySelector('.aiClose'),form=document.querySelector('.aiForm'),input=document.querySelector('#aiInput'),messages=document.querySelector('.aiMessages'),suggestions=document.querySelector('.aiSuggestions'),enable=document.querySelector('.enableAI'),status=document.querySelector('.aiStatus'),progress=document.querySelector('.aiProgress');
let engine=null,aiReady=false,loading=false,previousQuery='',lastBot='';const conversation=[];
function openPanel(){panel.inert=false;panel.classList.add('open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),100)}
function closePanel(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');panel.inert=true;fab?.focus()}
function addMessage(text,who='bot',extra=''){const d=document.createElement('div');d.className='aiMsg '+who+(extra?' '+extra:'');d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
async function ask(q){addMessage(q,'user');input.value='';panel.classList.add('engaged');suggestions?.setAttribute('aria-hidden','true');if(!inScope(q,previousQuery)){const refusal='I can only answer questions related to Mosin Shaikh, TTRL work, projects, professional services and technology.';addMessage(refusal);lastBot=refusal;previousQuery=q;return}conversation.push({role:'user',content:q});if(!aiReady){let answer=localAnswer(q,previousQuery);if(answer===lastBot)answer+=' To make this more specific, share the project type, required features and intended users.';addMessage(answer);conversation.push({role:'assistant',content:answer});lastBot=answer;previousQuery=q;return}const wait=addMessage('Thinking locally on your device…','bot','thinking');try{const reply=await engine.chat.completions.create({messages:[{role:'system',content:WORK_CONTEXT+'\nCURRENT RESPONSE INSTRUCTION: Reply in the same language and script as the user\'s latest message. Use the conversation only for context; use WORK_CONTEXT as the source of truth.'},...conversation.slice(-8)],temperature:.25,max_tokens:420});wait.remove();const answer=reply.choices[0].message.content.trim();addMessage(answer);conversation.push({role:'assistant',content:answer});lastBot=answer;previousQuery=q}catch(e){wait.remove();const answer='The local AI could not complete that response. Knowledge mode is still available. '+localAnswer(q,previousQuery);addMessage(answer);lastBot=answer;previousQuery=q}}
fab?.addEventListener('click',openPanel);closeAI?.addEventListener('click',closePanel);addEventListener('keydown',e=>{if(e.key==='Escape'&&panel?.classList.contains('open'))closePanel()});form?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(q)ask(q)});suggestions?.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')ask(e.target.textContent)});
enable?.addEventListener('click',async()=>{if(aiReady||loading)return;if(!('gpu'in navigator)){addMessage('On-device AI needs a WebGPU-compatible browser/device. Knowledge mode will continue to work without any download.');return}loading=true;enable.disabled=true;progress.hidden=false;addMessage('On-device AI setup started. This downloads a large model once and may use about 1 GB of device memory.');try{const webllm=await import('https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm@0.2.84/+esm');engine=await webllm.CreateMLCEngine('Qwen2.5-0.5B-Instruct-q4f16_1-MLC',{initProgressCallback:p=>{const n=Math.max(0,Math.min(100,Math.round((p.progress||0)*100)));progress.querySelector('span').style.width=n+'%';progress.querySelector('small').textContent=p.text||('Preparing local AI… '+n+'%')}});aiReady=true;const indicator=document.createElement('i');status.replaceChildren(indicator,document.createTextNode('On-device AI ready'));enable.textContent='AI enabled';progress.hidden=true;addMessage('On-device AI is ready. It runs in this browser without an API. Ask any work or technology question.')}catch(e){progress.hidden=true;enable.disabled=false;addMessage('This device could not start the local model. Knowledge mode remains fully available.');console.error(e)}finally{loading=false}});
